language: R
sudo: false
cache: packages
latex: false

r:
  - release
  - devel

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:edd/misc'
    packages:
      - libcurl4-openssl-dev
      - libprotobuf-dev 
      - libprotoc-dev 
      - protobuf-compiler 
      - libgoogle-perftools-dev

script:
- R CMD INSTALL .
- R CMD build .
- R CMD check *tar.gz

after_success:
  - Rscript -e 'covr::codecov()'

notifications:
  email:
    on_success: change
    on_failure: change
    
