language: R
sudo: false
cache: packages
latex: false

r:
  - release
  - devel

addons:
  apt:
    update: true
    sources:
      - sourceline: 'ppa:edd/misc'
    packages:
      - libcurl4-openssl-dev
      - libprotobuf-dev 
      - libprotoc-dev 
      - protobuf-compiler 
      - libgoogle-perftools-dev
      - libeigen3-dev

before_install:
  - python -c "import fcntl; fcntl.fcntl(1, fcntl.F_SETFL, 0)"  # https://github.com/travis-ci/travis-ci/issues/8920
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install g++-5 -y
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 100

after_success:
  - Rscript -e 'covr::codecov()'

after_failure:
  - python -c "import fcntl; fcntl.fcntl(1, fcntl.F_SETFL, 0)"  # https://github.com/travis-ci/travis-ci/issues/8920
  - sleep 20
  - cat /home/travis/build/tmelliott/transitr/transitr.Rcheck/00install.out && sleep 20;
  - if [ -f tests/tests.log ]; then cat tests/tests.log && sleep 20; fi
  - if [ -f tests/tests.log ]; then cat tests/tests.log && sleep 10; fi

notifications:
  email:
    on_success: change
    on_failure: change
    
