language: R
sudo: false
cache: packages

r:
 - release
 - devel

addons:
  apt:
    update: true
    sources:
     - sourceline: 'ppa:mhier/libboost-latest'
     - ubuntu-toolchain-r-test
    packages:
     - g++-6
     - boost1.67

after_success:
 - Rscript -e 'covr::codecov()'