#!/bin/sh

rm -f config.* src/Makevars \
    src/*.o src/*.d src/*.a src/*.dll src/*.so src/*.rc */*~ *~ \
    src/gtfs-realtime.pb.cc \
    src/vendor/protobuf/gtfs-realtime.pb.h

rm -rf inst/doc/auto autom4te.cache
