#!/bin/sh

rm -f config.log config.status \
    src/Makevars \
    src/*.o src/*.d src/*.a src/*.dll src/*.so src/*.rc */*~ *~ \
    src/vendor/protobuf/*.pb.* \
    src/vendor/sqlite3/sqlite3.o \
    src/vendor/rtnorm/rtnorm.o \
    transitr_*.tar.gz

rm -rf inst/doc/auto autom4te.cache transitr.Rcheck windows
