comment: false

# some files we don't develop outselves, so why test them ...? 
# (yes, probably should, but, ...)
ignore:
  - "src/vendor/**/*"
  - "src/gtfs-realtime.pb.cpp"
  - "src/realtime_main.cpp"   # cannot be tested (runs indefinitely)

codecov:
  branch: develop
  
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
    patch:
      default:
        target: auto
        threshold: 1%
