// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif


RcppExport SEXP _rcpp_module_boot_TripDescriptorModule();
RcppExport SEXP _rcpp_module_boot_VehicleModule();
RcppExport SEXP _rcpp_module_boot_RouteModule();
RcppExport SEXP _rcpp_module_boot_TripModule();

static const R_CallMethodDef CallEntries[] = {
    {"_rcpp_module_boot_TripDescriptorModule", (DL_FUNC) &_rcpp_module_boot_TripDescriptorModule, 0},
    {"_rcpp_module_boot_VehicleModule", (DL_FUNC) &_rcpp_module_boot_VehicleModule, 0},
    {"_rcpp_module_boot_RouteModule", (DL_FUNC) &_rcpp_module_boot_RouteModule, 0},
    {"_rcpp_module_boot_TripModule", (DL_FUNC) &_rcpp_module_boot_TripModule, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_transitr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
