# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

shapes_df_to_list <- function(x) {
    .Call('_transitr_shapes_df_to_list', PACKAGE = 'transitr', x)
}

