# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

construct_network <- function(nw, shapes) {
    .Call(`_transitr_construct_network`, nw, shapes)
}

processEtas <- function(files, out, dbname) {
    invisible(.Call(`_transitr_processEtas`, files, out, dbname))
}

shapes_df_to_list <- function(x) {
    .Call(`_transitr_shapes_df_to_list`, x)
}

calculate_shape_distance <- function(x) {
    .Call(`_transitr_calculate_shape_distance`, x)
}

run_realtime_model <- function(nw) {
    invisible(.Call(`_transitr_run_realtime_model`, nw))
}

